#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PCV_client.Resource", IsApplication=true)]

namespace PCV_client
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_black_notitlebar_fullscreen_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cursor = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int error = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int noconnection = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int pcviewer = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int readytoconnect = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int clearButton = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int connectButton = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int contentImg = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int imageView1 = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int ipEdit = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout2 = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int myview = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int portEdit = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int tableLayout2 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int tableRow4 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int tableRow5 = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int tableRow6 = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContentPage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
